# Nome do workflow
name: CI - Build e Push das Imagens Docker

# Gatilho: rodar em Pull Requests direcionados à branch 'develop'
on:
  pull_request:
    branches: [ develop ]

jobs:
  build-e-push:
    runs-on: ubuntu-latest
    steps:
      # 1. Faz o checkout do código do seu repositório
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. Faz o login no Azure Container Registry
      #    Esta etapa usa os secrets que acabamos de criar.
      - name: Login no Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # 3. Build e Push da imagem do Back-end
      - name: Build e Push da imagem do Back-end
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/backend:${{ github.sha }}

      # 4. Build e Push da imagem do Front-end
      - name: Build e Push da imagem do Front-end
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/frontend:${{ github.sha }}