# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: CI - Build e Teste

# Define o gatilho: rodar em Pull Requests direcionados à branch 'develop'
on:
  pull_request:
    branches: [ develop ]

# Define os jobs que o workflow executará
jobs:
  build-e-validacao:
    # O tipo de máquina virtual que o job rodará
    runs-on: ubuntu-latest

    # Os passos que compõem o job
    steps:
      # 1. Faz o checkout do código do seu repositório para a máquina virtual
      - name: Checkout do código
        uses: actions/checkout@v4

      # 2. (CORREÇÃO) Configura o QEMU, necessário para o passo seguinte
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      # 3. (CORREÇÃO) Configura o Docker Buildx, a ferramenta moderna de build do Docker
      # Esta action prepara o ambiente e habilita o comando 'docker compose'
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4. (CORREÇÃO) Executa o build usando o comando 'docker compose' (com espaço)
      - name: Build das imagens Docker com Compose V2
        run: docker compose build